### ISSUE TITLE
Issue Involving Captchas

### ISSUE THREAD

**Issue by ChrisPotts** [ryan9918/adidas-account-gen#4]
[17:27:41.100] Started account generator.
[17:27:41.100] Task 0 - Waiting for captcha token.
[2017-12-04 17:27:44,226] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 58, in submit
    captureToken(token)
  File "main.py", line 19, in captureToken
    expiry = datetime.now().timestamp() + 115
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by MoonDreamAL** [comment]
Im having the same exact error^

**Comment by ryan9918** [comment]
you using python2 and the readme says use python3. if you switch to using python3 you won't get that error.
